name: Deploy to Windows EC2 (Custom Folder)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean deployment folder
        run: |
          if exist "C:\deployments\portfolio" (
            rmdir /s /q "C:\deployments\portfolio"
          )
          mkdir "C:\deployments\portfolio"

      - name: Copy files
        run: |
          xcopy * "C:\deployments\portfolio\" /E /H /C /I /Y

      - name: Restart IIS
        run: |
          iisreset
