name: Deploy to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to IIS folder
        run: |
          xcopy * "C:\deployments\portfolio\" /E /H /C /I /Y || exit 0

      - name: Restart IIS
        run: iisreset
